# Análise de texto

In [14]:
# Importando as bibliotecas
import spacy
import pandas as pd 
from collections import Counter

In [15]:
# Carrega o modelo em português
nlp = spacy.load("pt_core_news_lg")

# Carrega o texto do arquivo .txt
with open("texto.txt", "r", encoding="utf-8") as arquivo:
    texto = arquivo.read()

# Processa o texto
doc = nlp(texto)

In [16]:
# Lista onde as informações serão armazenadas
dados = []

# Percorre todos os tokens
for token in doc:

    # Ignora pontuação e espaços
    if token.is_punct or token.is_space or token.is_stop:
        continue

    # Armazena as informações
    dados.append({
        "Palavra" : token.text,
        "Lema": token.lemma_,
        "Classe": token.pos_,
        "Detalhe": token.tag_
    })

In [17]:
# Cria o DataFrame com as informações 
df = pd.DataFrame(dados)
df

         Palavra        Lema Classe Detalhe
0       Exército    Exército  PROPN   PROPN
1     Brasileiro  Brasileiro  PROPN   PROPN
2     componente  componente   NOUN    NOUN
3      terrestre   terrestre    ADJ     ADJ
4         Forças      Forças  PROPN   PROPN
..           ...         ...    ...     ...
124     oficiais     oficial    ADJ     ADJ
125    sargentos    sargento   NOUN    NOUN
126  temporários  temporário    ADJ     ADJ
127            8           8    NUM     NUM
128         anos         ano   NOUN    NOUN

[129 rows x 4 columns]

In [18]:
df ['Classe'].value_counts()

Classe
NOUN     51
PROPN    31
ADJ      30
VERB     13
NUM       2
ADV       1
DET       1
Name: count, dtype: int64

In [22]:
# Frequência das palavras

frequencia = Counter(
    token.lemma_.lower()
    for token in doc
    if not token.is_punct
    and not token.is_space
    and not token.is_stop
)

df_freq = pd.DataFrame(frequencia.items(), columns=['Palavra', 'Contagem'])
df_freq.sort_values('Contagem', ascending=False).head(20)

         Palavra  Contagem
37      operação         3
49          área         3
59       militar         3
79       oficial         3
11      garantia         2
17         atuar         2
10      nacional         2
40     segurança         2
13         ordem         2
1     brasileiro         2
57         fazer         2
75           ano         2
81  profissional         2
76      processo         2
68   alistamento         2
12           lei         2
89      sargento         2
96    temporário         2
8         defesa         2
7    responsável         1